### ISSUE TITLE
error when importing exp on class ThickShapeStim

### ISSUE THREAD

**Issue by Foucl** [qbilius/psychopy_ext#9]
from psychopy_ext import exp fails with traceback:

```python
AttributeErrorTraceback (most recent call last)
<ipython-input-2-522cf00ccc56> in <module>()
----> 1 from psychopy_ext import exp

C:\Users\chdan\Anaconda2\lib\site-packages\psychopy_ext\exp.py in <module>()
   2125 
   2126 
-> 2127 class ThickShapeStim(visual.shape.ShapeStim):
   2128     """
   2129     Draws thick shape stimuli as a collection of lines.

AttributeError: 'module' object has no attribute 'shape'
```

Happens in jupyter notebook, console and in regular python. The namespace should be empty, I haven't called anything else before. `from psychopy.visual.shape import ShapeStim` works fine.

Windows 10, 64bit
Python 2.7.12 :: Anaconda 4.1.1 (64-bit)
psychopy_ext & psychopy (Version: 1.83.4) from pip

**Comment by qbilius** [comment]
Thanks for the detailed report. Should be fixed now. I pushed the updates to PyPI too so you should be able to update the package via pip.

**Comment by Foucl** [comment]
Can confirm that this works. Thank you so much for the quick fix and for sharing this package. I really am looking forward to using psychopy_ext (after having to work with Presentation). Still trying to convert my colleagues (especially those teaching research methods / data analysis) to Python though ...
